### ISSUE TITLE
Upgrade to postcss 4.0

### ISSUE THREAD

**Issue by yisibl** [hail2u/node-csswring#47]
https://github.com/postcss/postcss/releases/tag/4.0.0

**Comment by hail2u** [comment]
All right.

**Comment by austinpray** [comment]
What happened here?

**Comment by hail2u** [comment]
I've done: https://github.com/hail2u/node-csswring/tree/postcss-v4

However I can't decide to increment major version of this package now. Wait for a while!

**Comment by MoOx** [comment]
Is there a blocker?

**Comment by austinpray** [comment]
Can I help out at all with getting v4 out the door?

**Comment by hail2u** [comment]
Released v3.0.0.
