### ISSUE TITLE
two attribute selectors combine into one when first attribute has = in it

### ISSUE THREAD

**Issue by jpweller** [hail2u/node-csswring#48]
input[type="radio"][disabled]

outputs:

      input[type="radio][disabled"]

but

      input[disabled][type="radio"]

outputs: 

      input[disabled][type=radio]

**Comment by MoOx** [comment]
@hail2u you should use [balanced-match](https://www.npmjs.com/package/balanced-match) to handle this kind of problem :)

**Comment by hail2u** [comment]
Thanks, reproduced.

@MoOx balanced-match looks very nice.

**Comment by hail2u** [comment]
I have fixed regular expression for attribute selector, but this doesn't seem perfect. Using balanced-match should work as expected against nested square brackets, but I don't know this can handle non-escaped closing square bracket in quote (`[foo='fo]']`) and escaped closing square bracket (`[foo=fo\]o]`).
