### ISSUE TITLE
Unquoting url() fails if url contains ")"

### ISSUE THREAD

**Issue by Pumpuli** [hail2u/node-csswring#54]
If a url is quoted and it has ")" somewhere inside, the urlFunction regexp fails. For example LESS' [svg-gradient function](http://lesscss.org/functions/#misc-functions-svg-gradient) outputs such urls.

Truncated example from their site:

    background-image: url('data:image/svg+xml,%3C........%22url(%23gradient)%22%20%2F%3E%3C%2Fsvg%3E');

csswring gives

    background-image: url("'data:image/svg+xml,%3C........%22url(%23gradient")%22%20%2F%3E%3C%2Fsvg%3E');

**Comment by hail2u** [comment]
Thanks. Fixed by updating RegExp. I will release new version next week with this fix.
