### ISSUE TITLE
Option to preserve % sign on flex values (needed for correct IE10/11 behaviour)

### ISSUE THREAD

**Issue by benfrain** [hail2u/node-csswring#57]
Hi,

Is there any chance of getting an option to preserve the % sign on flex properties. This is to avoid a known flexbox bug in IE 10/11.

At present writing this:

flex: 1 0 0%;

Gets minified to:

flex:1 0 0;

And this breaks IE10/11. Just need the % preserving on flex properties. https://github.com/philipwalton/flexbugs#4-flex-shorthand-declarations-with-unitless-flex-basis-values-are-ignored

**Comment by hail2u** [comment]
Sorry for late action. This will release in next few days!
