### ISSUE TITLE
Deprecation notices with PostCSS

### ISSUE THREAD

**Issue by elimc** [hail2u/node-csswring#61]
I'm receiving numerous deprecation notices when I run my default gulp task:

```javascript
Node#semicolon is deprecated. Use Node#raws.semicolon
Node#after is deprecated. Use Node#raws.after
Container#eachComment is deprecated. Use Container#walkComments instead.
Node#before is deprecated. Use Node#raws.before
Node#removeSelf is deprecated. Use Node#remove.
Node#before is deprecated. Use Node#raws.before
Node#removeSelf is deprecated. Use Node#remove.
Container#eachDecl is deprecated. Use Container#walkDecls instead.
Node#between is deprecated. Use Node#raws.between
Node#_important was deprecated. Use Node#raws.important
Container#eachRule is deprecated. Use Container#walkRules instead.
Node#semicolon is deprecated. Use Node#raws.semicolon
Node#after is deprecated. Use Node#raws.after
Container#eachAtRule is deprecated. Use Container#walkAtRules instead.
AtRule#afterName was deprecated. Use AtRule#raws.afterName
```

I have narrowed the issue to csswring. When csswring is commented out, the deprecation errors disappear.

I ran ```npm ls postcss``` in the CLI. I received the following:

```javascript
├─┬ autoprefixer@6.0.3
│ └── postcss@5.0.10
├─┬ css-mqpacker@4.0.0
│ └── postcss@5.0.10
├─┬ csswring@3.0.7
│ └── postcss@4.1.16
├─┬ gulp-postcss@6.0.1
│ └── postcss@5.0.10
├─┬ lost@6.6.2
│ └── postcss@5.0.10
└─┬ precss@1.2.3
  └── postcss@5.0.10
```

This confirms that csswring is using an older version of postcss as a dependency and is the source of the issue.

I am currently running Node v4.2.0 and gulp 4.0.0.

While the compilation and wringing process still works, the deprecation notices add at least 100ms to the build process. It also confuses new users as to why they are receiving this error message.

**Comment by hail2u** [comment]
csswring v4.0.0 has been released already. You should update `package.json`.
