### ISSUE TITLE
Quotes are removed from single hyphen attribute-selector

### ISSUE THREAD

**Issue by kgram** [hail2u/node-csswring#69]
An attribute-selector like `[data-attr*="-"]` is minified to `[data-attr*=-]`. This is wrong, see http://stackoverflow.com/questions/34771373/unquoted-hyphen-in-attribute-selector. As a consequence, this selector will be ignored by browsers after minification. This is only a problem when the string is exactly a single hyphen.

**Comment by hail2u** [comment]
Thanks. Updated version will be released soon.
