### ISSUE TITLE
native css variables are quoted in font-family

### ISSUE THREAD

**Issue by kmohrf** [hail2u/node-csswring#70]
hej,

thanks for working on csswring. i’ve spotted a bug in the way native css variables are handled in font-family declarations. consider the following input:

```
:root {
    --foo: "foo";
    --bar: 0;
    font-family: var(--foo);
    width: var(--bar);
}
```

and output:

`:root{--foo:"foo";--bar:0;font-family:"var(--foo)";width:var(--bar)}`

Though the width declaration is fine the font-family is quoted, rendering the var function useless. I’d expect csswring to leave the font-family value/values intact, if the value is enclosed by a var function. I’ve been using csswring 4.2.1 to generate this output.

thanks!

**Comment by hail2u** [comment]
Thanks, it’s reproduced. We should treat a `var()` function as special case.

**Comment by kmohrf** [comment]
that was fast. chapeau!
