### ISSUE TITLE
Keep font-family quotes (IE BREAKS)

### ISSUE THREAD

**Issue by OZZlE** [hail2u/node-csswring#74]
All modern browser don't support unquoted font-families... It does NOT work in IE10, IE11, Edge...

Please keep it or at least add an option to preserve it..

Please test it in IE using the test case in the source here and you can see that it IS valid.

SOURCE: https://connect.microsoft.com/IE/feedbackdetail/view/1957543/

**Comment by hail2u** [comment]
Reproduced on IE11, but not on Edge. I’ll looking into more.

**Comment by hail2u** [comment]
In my test on IE11, this bug seems to occur on an unquoted `local()` function only, not by an unquoted value of `font-family` property (or descriptor). CSSWring does not touch quotes inside `local()` function.  Quotes inside `local()` are always kept.
