### ISSUE TITLE
Calc(0px) rewritten as calc(0)

### ISSUE THREAD

**Issue by gil--** [hail2u/node-csswring#77]
When doing something like:

`margin-top: calc(0px)`, csswring rewrites the value to `calc(0)` which is invalid and breaks in the browser. I'm using *calc(0px)* as a fallback override and have had to disable csswring at the moment to avoid breaking my CSS.

I assume it's this regex of 0 properties dropping their unit value causing the issue: https://github.com/hail2u/node-csswring/blob/master/lib/regexp.js#L90

**Comment by hail2u** [comment]
This was fixed already in #62.

![cap-20160607-100106](https://cloud.githubusercontent.com/assets/68940/15842745/c78455c2-2c96-11e6-82c8-15a28a92884e.png)

**Comment by gil--** [comment]
@hail2u Thanks for pointing this out. I've updated csswring and postcss to  latest and it works perfectly now.
