### ISSUE TITLE
Option to preserve % sign on min-width (needed for correct IE10/11 behaviour)

### ISSUE THREAD

**Issue by oilvier** [hail2u/node-csswring#89]
Hi,

Is there any chance of getting an option to preserve the % sign on min-width ? This is to avoid a flexbox bug in IE 10/11.

The classic fix is to use unitless `min-width:0;` (cf: https://blog.goetter.fr/2016/11/09/flexbox-min-width-0-is-the-new-zoom-1/, in French) but it seems in IE 10/11 you need to add a `%` for the fix to work properly. (IE convert unitless 0 to `0px`).

At present writing this:

`min-width:0%;`

Gets minified to:

`min-width:0;`

And this breaks IE10/11. Just need the % preserving on `min-width:0%`.

**Comment by hail2u** [comment]
If I understand correctly, this seems a IE10/11 bug and solution is some sort of CSS hack. I preserve a percent unit only under the `preserveHacks: true` option. Is this OK?

**Comment by oilvier** [comment]
Yes, thank you !
